[tool.poetry]
name = "plantai"
version = "0.1.0"
description = ""
authors = ["Shinkenuu <shinkenuu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.9,<3.12"
transformers = "^4.34.1"
torch = "2.0.0"
langchain = "0.0.339"
openai = "1.3.5"
bitsandbytes = "^0.41.1"
accelerate = "^0.24.1"
xformer = "^1.0.1"
chainlit = "^0.7.700"
duckduckgo-search = "^4.1.0"
langchainhub = "^0.1.14"
openllm = "^0.4.41"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
black = "^23.10.1"
ruff = "^0.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
